name: waassist
description: |
  Status saver, 30 days status backup, chat without saving number and many more.

  WA Assist is a integrated platform to simplify the experience of using WhatsApp.

  ðƒðžðð¢ðœðšð­ðžð ð’ð®ð©ð©ð¨ð«ð­ ð…ð¨ð« :
     - WhatsApp
     - Dual WhatsApp
     - WhatsApp Business
     - Dual WhatsApp Business

  ð“ð¨ð© ð…ðžðšð­ð®ð«ðžð¬ :
     -  Save, delete and view WhatsApp status.
     -  Backup for up to ðŸ‘ðŸŽ ððšð²ð¬ old status.
     -  Start chat ð°ð¢ð­ð¡ð¨ð®ð­ ð¬ðšð¯ð¢ð§ð  number.

  ðŽð­ð¡ðžð« ð…ðžðšð­ð®ð«ðžð¬ :
     -  Expression Cartoon
     -  100x ð³ð¨ð¨ð¦ to view image.
     -  20000+ prebuilt short videos.
     -  Left-Right Swipe to preview image/video.

  WA Assist act like a WhatsApp Assist or WhatsApp assistant to save time. It helps to minimize effort in search of better resources for quality content.

  We hope you'll feel better and enjoy using WA Assist as much as we enjoyed developing it. Looking forward to your participation in creating this platform more reliable for the high quality facilities.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.5
  permission_handler: ^8.2.5
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.0.6
  google_mobile_ads: ^1.0.0
  provider: ^6.0.1
  intl: ^0.17.0
  http: ^0.13.4
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  package_info: ^2.0.2
  country_picker: ^2.0.8
  url_launcher: ^6.0.12
  webview_flutter: ^2.3.0
  share_plus: ^3.0.4
  connectivity: ^3.0.6
  video_player: ^2.2.6
  # To get .mapIndexed facility
  collection: ^1.15.0
  flutter_downloader: ^1.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Flutter Icon and Splash is not working at once use one by one
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: true
  # ios: true
  image_path: "assets/logo_rounded.png"
  adaptive_icon_background: "#FFFFFF"
  #240E7B
  adaptive_icon_foreground: "assets/logo.png"

# flutter_native_splash:
#   # flutter pub run flutter_native_splash:create

#   color: "#ffffff"
#   #background_image: "assets/background.png"
#   # The image parameter allows you to specify an image used in the splash screen.  It must be a
#   # png file.
#   image: assets/logo_rounded.png

#   android: true
#   ios: false
#   web: false
#   android_gravity: center
#   fullscreen: false

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fileImage.png
    - assets/cat1.webp
    - assets/cat2.webp
    - assets/cat3.webp
    - assets/not_found.png
    - assets/wa.png
    - assets/dwa.png
    - assets/wab.png
    - assets/dwab.png
    - assets/logo.png
    - assets/logo_edge.png
    - assets/logo_rounded.png
    - assets/facebook.png
    - assets/twitter.jpg
    - assets/instagram.png
    - assets/linkedin.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # example:
  fonts:
    - family: Signika
      fonts:
        - asset: fonts/Signika-Bold.ttf
          weight: 700
        - asset: fonts/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika-Medium.ttf
          weight: 500
        - asset: fonts/Signika-Regular.ttf
          weight: 400
        - asset: fonts/Signika-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
